version: '3.8'
services:
  verytune-backend:
    build: 
      context: backend
      target: verytune-backend-dev
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    restart: always
    depends_on:
      - verytune-database
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
      # mount code
      - ./backend:/srv/app
      # speeds up the compiling
      - /srv/app/node_modules
    networks:
      - verytune
      
  verytune-frontend:
    build: 
      context: frontend
      target: verytune-frontend-dev
      dockerfile: Dockerfile
    ports: 
      - "3100:3100"
    restart: always
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
      # mount code
      - ./frontend:/srv/app
      # speeds up the compiling
      - /srv/app/node_modules
    networks:
      - verytune

  verytune-database: 
    image: mongo:latest
    networks:
      - verytune
    ports: 
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: password

networks: 
  verytune: